### ISSUE TITLE
old URL needs to be redirected to new page for Sherman Copy article

### ISSUE THREAD

**Issue by JScheick** [dbactual/thomaspaine#15]
The old URL for the Sherman Copy article needs to be redirected to the new page: 

Old URL:  https://www.thomaspaine.org/aboutpaine/sherman-copy-di.html
 
New Page (New URL):  https://thomaspaine.org/pages/resources/sherman-copy-di.html

All current internet searches for Sherman Copy article are led to error message b/c old page is not yet redirected to new page.  

Thank you for your assistance.

**Comment by dbactual** [comment]
Thanks for the report! Work is currently in-progress to fix this and related issues. See https://github.com/dbactual/thomaspaine/pull/14

**Comment by JScheick** [comment]
Thank you, Dave!  You're amazing!

Regards,
Jonathan


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by dbactual** [comment]
Fixed and deployed to the live site.

**Comment by JScheick** [comment]
Fantastic. Thank you again, Dave!
I greatly appreciate your expertise.

Regards,
Jonathan

Sent from my iPhone

On Jun 28, 2022, at 4:44 PM, Dave Berton ***@***.***> wrote:

﻿

Fixed and deployed to the live site.

**Comment by tompainetoday** [comment]
all working! nice work team!
